version: "3.9"
services:
  spigot:
    build:
      context: ./spigot
      args:
        MINECRAFT_VERSION: 1.16.5
    stdin_open: true
    tty: true
    ports:
      - "25565:25565"
    volumes:
      - ./spigot/server:/server/data
